# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [4]:


import numpy as np

# Convert lists to numpy arrays
height = np.array([69, 70, 71, 72, 73, 74, 75])
weight = np.array([110, 120, 130, 140, 150, 160, 170])

# Calculate BMI: weight / (height**2) * 730
BMI = weight / (height ** 2) * 730

# Print the BMI values
print(BMI)


[16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
 22.06222222]


### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [5]:
import numpy as np

def generate_random_matrix(rows, cols, dtype=float, shape=None):
    """
    Generate a random matrix.

    Parameters:
    - rows (int): Number of rows.
    - cols (int): Number of columns.
    - dtype (data-type): Desired data-type for the matrix. Default is float.
    - shape (tuple): Desired shape of the matrix. If provided, rows and cols are ignored.

    Returns:
    - np.ndarray: Generated random matrix.
    """
    if shape:
        return np.random.rand(*shape).astype(dtype)
    else:
        return np.random.rand(rows, cols).astype(dtype)

# Example usage:
matrix = generate_random_matrix(3, 4, dtype=np.int32)
print(matrix)

# Using shape parameter
matrix_with_shape = generate_random_matrix(3, 4, dtype=np.float64, shape=(5, 5))
print(matrix_with_shape)



[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[2.42814431e-01 1.14294897e-01 6.83167729e-01 7.40312529e-01
  4.40152314e-01]
 [9.29596057e-05 5.02409024e-01 9.05312202e-01 3.20678582e-01
  8.60250231e-01]
 [2.85663604e-01 1.76489282e-01 2.64120285e-01 6.17828154e-02
  3.83033648e-01]
 [3.14211983e-01 2.53687687e-01 1.51016620e-01 6.95644993e-01
  9.27452348e-01]
 [2.69550642e-01 8.89679868e-01 1.34975900e-01 8.51908333e-01
  4.27263992e-02]]


### #3 - Extra: Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [11]:
import csv
import numpy as np
import os

def load_slg_data(filename):
    """
    Load SLG data from a CSV file.

    Parameters:
    - filename (str): The path to the CSV file.

    Returns:
    - np.ndarray: An array of SLG values.
    """
    slg_values = []
    try:
        with open(filename, 'r') as file:
            reader = csv.DictReader(file)
            for row in reader:
                try:
                    slg_values.append(float(row['SLG']))
                except ValueError:
                    print(f"Error: Invalid SLG value '{row['SLG']}' in file '{filename}'.")
                    return None
    except FileNotFoundError:
        print(f"Error: The file '{filename}' was not found.")
        return None
    except KeyError:
        print(f"Error: The file '{filename}' does not contain a 'SLG' column.")
        return None
    return np.array(slg_values)


print("Current working directory:", os.getcwd())

path_2017 = 'redsox_2017_hitting.txt'
path_2018 = 'redsox_2018_hitting.txt'


slg_2017 = load_slg_data(path_2017)
slg_2018 = load_slg_data(path_2018)


if slg_2017 is not None and slg_2018 is not None:
    
    avg_slg_2017 = np.mean(slg_2017)
    avg_slg_2018 = np.mean(slg_2018)

    # Determine which year was better based on SLG
    better_year = "2018" if avg_slg_2018 > avg_slg_2017 else "2017"

    print(f"Average SLG in 2017: {avg_slg_2017}")
    print(f"Average SLG in 2018: {avg_slg_2018}")
    print(f"The better year based on SLG is: {better_year}")
else:
    print("Data could not be loaded for comparison.")


Current working directory: c:\Users\Litzy\Downloads
Average SLG in 2017: 0.39334782608695656
Average SLG in 2018: 0.38750000000000007
The better year based on SLG is: 2017


In [ ]:
FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray


